# Site settings
title: Polyculture Kombucha
description: >
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: ""
url: "http://polyculturekombucha.com"
timezone: America/Detroit

# Build settings
permalink: /:categories/:title
imagePath: /resources/images
exclude: [vendor, Gemfile, Gemfile.lock]
markdown: kramdown
kramdown:
  auto_ids: false
sass:
  sass_dir: resources/_scss
  style: :compressed
