# Site settings
title: Polyculture Kombucha
description: >
  From the forests and fields of lovely Maple City comes Polyculture, Leelanau's very own brew!
baseurl: ""
url: "http://polyculturekombucha.com"
timezone: America/Detroit

# Build settings
permalink: /:categories/:title
imagePath: /resources/images
exclude: [vendor, Gemfile, Gemfile.lock]
markdown: kramdown
kramdown:
  auto_ids: false
sass:
  sass_dir: resources/_scss
  style: :compressed

# Defaults
defaults:
-
  scope:
    type: "posts"
  values:
    layout: "post"
    category: "blog"
